WIP PR to get the ball rolling
operator-framework/operator-framework.io pull request #14
Opened 2020-11-17 20:44 UTC by awgreene

2020-11-17 20:51 UTC, asmacdo approved these changes
Already a huge improvement. Once the "persona persona persona" replacement text renders correctly, I think this can merge.

2020-11-17 20:51 UTC, asmacdo commented on content/what.html
> +        <p class="large-text"><span>Software Engineers, </span>
might have to use a different class, its doing something funky 
![Screenshot from 2020-11-17 15-50-12](https://user-images.githubusercontent.com/1028657/99446144-9f017d80-28ec-11eb-928b-27b817b3803f.png)

2020-11-17 20:56 UTC, dmesser requested changes

2020-11-17 20:56 UTC, dmesser commented on content/what.html
> +        <span>Kubernetes Users, </span>
Wouldn't OperatorHub.io also appeal to Operator Developers to publish their work?

2020-11-17 20:56 UTC, dmesser commented on content/what.html
> +        <span>Cluster Admins.</span></p>
I wonder if we can convey here that the best people to write an Operators are the owners / developer of said application and SRE folks. WDYT?

2020-11-17 21:17 UTC, awgreene commented on content/what.html
> +        <span>Kubernetes Users, </span>
Good idea! I've updated the doc!

2020-11-17 21:17 UTC, awgreene commented on content/what.html
> +        <span>Cluster Admins.</span></p>
I think the updated commit makes this point clearer as well!

2020-11-17 21:18 UTC, awgreene commented on content/what.html
> +        <p class="large-text"><span>Software Engineers, </span>
I've had to revert to one-word names of personas, please review.

2020-11-17 21:20 UTC, asmacdo commented on content/what.html
> +        <span>Admins.</span></p>
:+1:

2020-11-17 21:49 UTC, asmacdo approved these changes

2020-11-18 11:46 UTC, dmesser approved these changes

2020-11-18 11:47 UTC, merged